version: "3"
services:
  scraper-db:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=changepassword
      - POSTGRES_DB=postgresdb
    volumes:
      - ./docker-data/postgres-logs:/var/log/postgresql
      - ./docker-data/postgres-data:/var/lib/postgresql/data
      - ./src/databases/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: scraper-db
    restart: on-failure
    networks:
      - server-network

  scraper-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - APP_NAME=main:app
      - APP_ADMIN_USER=administrator
      - APP_ADMIN_PASS=administrator
      - AUTH_SECRET_KEY=secret
      - AUTH_ALGORITHM=HS256
      - AUTH_EXPIRE_MINUTES=30
      - LOG_APP_PATH=/var/log/scraper-anime/app.log
      - LOG_ERROR_PATH=/var/log/scraper-anime/error.log
      - POSTGRES_HOST=scraper-db
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASS=changepassword
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgresdb
    volumes:
      - ./docker-data/app-logs:/var/log/scraper-anime
    depends_on:
      - scraper-db
    container_name: scraper-api
    restart: on-failure
    networks:
      - server-network

networks:
  server-network:
    external: true
